mysql:
  host:
  port:
  user:
  pass:
  db:
firstloginmsg: '§d初めてログインしてくれてありがとう❤'
loginmsg: '§aログインしてくれてありがとう❤'
firstloginbonus:
  - say <player>さんが初参加です❤
loginbonus:
  - say <player>さんがログボゲットです❤
spawnpoint:
  world: world
  x: 0
  y: 0
  z: 0