name: BloomingRPGCore
version: ${project.version}
main: jp.mkserver.bloom.bloomingrpgcore.BloomingRPGCore
authors: [Mr_IK]
description: Minecraft JE server Blooming RPG Plugin.
depend: [Citizens,CrackShot]
commands:
  party:
    description: BloomParty
    usage: /<command>
    default: op
  pt:
    description: BloomParty
    usage: /<command>
    default: op
  skillpoint:
    description: BloomSkill
    usage: /<command>
    default: op
  sp:
    description: BloomSkill
    usage: /<command>
    default: op
  spawn:
    description: BloomSpawn
    usage: /<command>
    default: op